export default [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 40,
    spoonacularScore: 70.0,
    healthScore: 14.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.89,
    extendedIngredients: [
      {
        id: 18079,
        aisle: "Pasta and Rice",
        image: "breadcrumbs.jpg",
        consistency: "solid",
        name: "breadcrumbs",
        nameClean: "breadcrumbs",
        original: "1/2 cup of breadcrumbs",
        originalString: "1/2 cup of breadcrumbs",
        originalName: "breadcrumbs",
        amount: 0.5,
        unit: "cup",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11485,
        aisle: "Produce",
        image: "butternut-squash.jpg",
        consistency: "solid",
        name: "butternut squash",
        nameClean: "butternut squash",
        original: "1 1/2 cup of pureed butternut squash",
        originalString: "1 1/2 cup of pureed butternut squash",
        originalName: "pureed butternut squash",
        amount: 1.5,
        unit: "cup",
        meta: ["pureed"],
        metaInformation: ["pureed"],
        measures: {
          us: { amount: 1.5, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 354.882,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10120499,
        aisle: "Pasta and Rice",
        image: "elbow.jpg",
        consistency: "solid",
        name: "elbow macaroni",
        nameClean: "elbow macaroni",
        original: "1 box of elbow Macaroni",
        originalString: "1 box of elbow Macaroni",
        originalName: "elbow Macaroni",
        amount: 1.0,
        unit: "box",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "box", unitLong: "box" },
          metric: { amount: 1.0, unitShort: "box", unitLong: "box" },
        },
      },
      {
        id: 93690,
        aisle: "Spices and Seasonings;Health Foods",
        image: "nutritional-yeast.png",
        consistency: "solid",
        name: "nutritional yeast",
        nameClean: "nutritional yeast flakes",
        original: "3 tbsp of nutritional yeast",
        originalString: "3 tbsp of nutritional yeast",
        originalName: "nutritional yeast",
        amount: 3.0,
        unit: "tbsp",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: {
            amount: 3.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "solid",
        name: "pepper",
        nameClean: "ground black pepper",
        original: "A Dash of black Pepper",
        originalString: "A Dash of black Pepper",
        originalName: "A of black Pepper",
        amount: 1.0,
        unit: "Dash",
        meta: ["black"],
        metaInformation: ["black"],
        measures: {
          us: { amount: 1.0, unitShort: "Dash", unitLong: "Dash" },
          metric: { amount: 1.0, unitShort: "Dash", unitLong: "Dash" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "solid",
        name: "salt",
        nameClean: "salt",
        original: "A dash of salt",
        originalString: "A dash of salt",
        originalName: "A of salt",
        amount: 1.0,
        unit: "dash",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "dash", unitLong: "dash" },
          metric: { amount: 1.0, unitShort: "dash", unitLong: "dash" },
        },
      },
      {
        id: 16223,
        aisle: "Milk, Eggs, Other Dairy",
        image: "soy-milk.jpg",
        consistency: "liquid",
        name: "soy milk",
        nameClean: "soymilk",
        original: "2 cups light soy milk",
        originalString: "2 cups light soy milk",
        originalName: "light soy milk",
        amount: 2.0,
        unit: "cups",
        meta: ["light"],
        metaInformation: ["light"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 4673,
        aisle: "Milk, Eggs, Other Dairy",
        image: "light-buttery-spread.png",
        consistency: "solid",
        name: "vegan buttery spread",
        nameClean: "soy buttery spread",
        original: "1 tablespoons vegan buttery spread",
        originalString: "1 tablespoons vegan buttery spread",
        originalName: "vegan buttery spread",
        amount: 1.0,
        unit: "tablespoons",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 10193701,
        aisle: "Cheese;Health Foods",
        image: "cheddar-cheese.png",
        consistency: "solid",
        name: "vegan cheddar cheese",
        nameClean: "vegan cheddar cheese",
        original: "1 cup Daiya style vegan Cheddar Shreds",
        originalString: "1 cup Daiya style vegan Cheddar Shreds",
        originalName: "Daiya style vegan Cheddar Shreds",
        amount: 1.0,
        unit: "cup",
        meta: ["daiya style"],
        metaInformation: ["daiya style"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "liquid",
        name: "water",
        nameClean: "water",
        original: "4 cups water",
        originalString: "4 cups water",
        originalName: "water",
        amount: 4.0,
        unit: "cups",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 4.0, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 946.352,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 640720,
    title: "Creamy Vegan Butternut Squash Mac and Cheese",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "http://www.foodista.com/recipe/W2G2NLXR/creamy-vegan-butternut-squash-mac-and-cheese",
    image: "https://spoonacular.com/recipeImages/640720-556x370.jpg",
    imageType: "jpg",
    summary:
      'Creamy Vegan Butternut Squash Mac and Cheese might be just the side dish you are searching for. One serving contains <b>312 calories</b>, <b>11g of protein</b>, and <b>8g of fat</b>. This dairy free recipe serves 6 and costs <b>88 cents per serving</b>. 40 people have made this recipe and would make it again. From preparation to the plate, this recipe takes around <b>45 minutes</b>. If you have water, nutritional yeast, vegan buttery spread, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 66%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/vegan-mac-n-peas-with-creamy-butternut-squash-sauce-690179">Vegan Mac ‘n Peas with Creamy Butternut Squash Sauce</a>, <a href="https://spoonacular.com/recipes/creamy-butternut-squash-soup-vegan-winner-of-go-veggie-511040">Creamy Butternut Squash Soup (Vegan) / Winner of GO Veggie</a>, and <a href="https://spoonacular.com/recipes/creamy-vegan-butternut-squash-linguine-with-peas-and-kale-610789">Creamy Vegan Butternut Squash Linguine with Peas and Kale</a> for similar recipes.',
    cuisines: ["American"],
    dishTypes: ["side dish"],
    diets: ["dairy free"],
    occasions: [],
    instructions:
      "<ol><li> Begin by Preheating oven to 350</li><li>Bring a large pot of salted water to a boil over medium heat, add in elbows and cook until pasta is al dente.</li><li>While waiting for pasta to cook begin preparing your sauce. In a medium size sauce pan, melt butter over medium heat, add in nutritional yeast and mix together to form a paste</li><li>Add in soy milk, using a whisk combine together ingredients make sure your sauce is lump free, let simmer for 5 minute or until sauce begins to thicken</li><li>Add is pureed butternut squash, thoroughly mix together ingredients to ensure everything is well blended (you may notice that the butternut squash also helps to thicken the sauce).</li><li>Stir in Cheese, let sit for 1 to 2 minutes or until sauce has a creamy velvety smooth consistency. Remove Sauce from heat and let sit</li><li>Drain pasta and add pasta to the cheese sauce, stir together and pour mixture into a greased 9 x 9 baking pan</li><li>Sprinkle breadcrumbs over macaroni and cheese and let bake for 15 minutes or until cheese begins to bubble</li><li>Serve Warm and enjoy this creamy Vegan home-style comfort food!</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Begin by Preheating oven to 350Bring a large pot of salted water to a boil over medium heat, add in elbows and cook until pasta is al dente.While waiting for pasta to cook begin preparing your sauce. In a medium size sauce pan, melt butter over medium heat, add in nutritional yeast and mix together to form a paste",
            ingredients: [
              {
                id: 93690,
                name: "nutritional yeast",
                localizedName: "nutritional yeast",
                image: "nutritional-yeast.png",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 2,
            step:
              "Add in soy milk, using a whisk combine together ingredients make sure your sauce is lump free, let simmer for 5 minute or until sauce begins to thicken",
            ingredients: [
              {
                id: 16223,
                name: "soymilk",
                localizedName: "soymilk",
                image: "soy-milk.jpg",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image: "whisk.png",
              },
            ],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 3,
            step:
              "Add is pureed butternut squash, thoroughly mix together ingredients to ensure everything is well blended (you may notice that the butternut squash also helps to thicken the sauce).Stir in Cheese, let sit for 1 to 2 minutes or until sauce has a creamy velvety smooth consistency.",
            ingredients: [
              {
                id: 11485,
                name: "butternut squash",
                localizedName: "butternut squash",
                image: "butternut-squash.jpg",
              },
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [],
            length: { number: 1, unit: "minutes" },
          },
          {
            number: 4,
            step: "Remove Sauce from heat and let sit",
            ingredients: [
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step:
              "Drain pasta and add pasta to the cheese sauce, stir together and pour mixture into a greased 9 x 9 baking pan",
            ingredients: [
              {
                id: 0,
                name: "cheese sauce",
                localizedName: "cheese sauce",
                image: "",
              },
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 6,
            step:
              "Sprinkle breadcrumbs over macaroni and cheese and let bake for 15 minutes or until cheese begins to bubble",
            ingredients: [
              {
                id: 32004,
                name: "macaroni and cheese",
                localizedName: "macaroni and cheese",
                image: "macaroni-and-cheese.png",
              },
              {
                id: 18079,
                name: "breadcrumbs",
                localizedName: "breadcrumbs",
                image: "breadcrumbs.jpg",
              },
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: { number: 15, unit: "minutes" },
          },
          {
            number: 7,
            step:
              "Serve Warm and enjoy this creamy Vegan home-style comfort food!",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/creamy-vegan-butternut-squash-mac-and-cheese-640720",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 139,
    spoonacularScore: 70.0,
    healthScore: 12.0,
    creditsText: "Afrolems",
    license: "CC BY 4.0",
    sourceName: "Afrolems",
    pricePerServing: 143.8,
    extendedIngredients: [
      {
        id: 93607,
        aisle: "Milk, Eggs, Other Dairy",
        image: "almond-milk.png",
        consistency: "liquid",
        name: "almond milk",
        nameClean: "almond milk",
        original: "1/2 cup of almond milk (you can use regular milk)",
        originalString: "1/2 cup of almond milk (you can use regular milk)",
        originalName: "almond milk (you can use regular milk)",
        amount: 0.5,
        unit: "cup",
        meta: ["canned", "(you can use regular milk)"],
        metaInformation: ["canned", "(you can use regular milk)"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9040,
        aisle: "Produce",
        image: "bananas.jpg",
        consistency: "solid",
        name: "banana",
        nameClean: "banana",
        original: "1 large banana",
        originalString: "1 large banana",
        originalName: "banana",
        amount: 1.0,
        unit: "large",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "large", unitLong: "large" },
          metric: {
            amount: 1.0,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 14317,
        aisle: "Tea and Coffee",
        image: "cocoa-powder.png",
        consistency: "solid",
        name: "chocolate malt powder",
        nameClean: "chocolate malt powder",
        original: "1 tablespoon Milo chocolate malt powder",
        originalString: "1 tablespoon Milo chocolate malt powder",
        originalName: "Milo chocolate malt powder",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        nameClean: "strawberries",
        original: "Handful of chopped strawberries",
        originalString: "Handful of chopped strawberries",
        originalName: "chopped strawberries",
        amount: 1.0,
        unit: "Handful",
        meta: ["chopped"],
        metaInformation: ["chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
          metric: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
        },
      },
      {
        id: 19095,
        aisle: "Frozen",
        image: "vanilla-ice-cream.png",
        consistency: "solid",
        name: "vanilla ice cream",
        nameClean: "vanilla ice cream",
        original: "2 tablespoons of vanilla ice-cream",
        originalString: "2 tablespoons of vanilla ice-cream",
        originalName: "vanilla ice-cream",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 1054,
        aisle: "Milk, Eggs, Other Dairy",
        image: "whipped-cream.jpg",
        consistency: "solid",
        name: "whipped cream",
        nameClean: "whipped cream",
        original: "1/4 cup of whipped cream",
        originalString: "1/4 cup of whipped cream",
        originalName: "whipped cream",
        amount: 0.25,
        unit: "cup",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 716351,
    title: "Banana Milo Milkshake",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.afrolems.com/2015/02/10/banana-milo-milkshake/",
    image: "https://spoonacular.com/recipeImages/716351-556x370.jpg",
    imageType: "jpg",
    summary:
      'You can never have too many beverage recipes, so give Banana Milo Milkshake a try. For <b>$1.41 per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. This recipe makes 1 servings with <b>268 calories</b>, <b>4g of protein</b>, and <b>9g of fat</b> each. 139 people have made this recipe and would make it again. A mixture of handful of strawberries, banana, whipped cream, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 70%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/galletas-de-milo-milo-cookies-226942">Galletas de Milo (Milo Cookies)</a>, <a href="https://spoonacular.com/recipes/strawberry-banana-milkshake-milkshake-without-ice-cream-600499">Strawberry Banana Milkshake | Milkshake without ice cream</a>, and <a href="https://spoonacular.com/recipes/banana-milkshake-how-to-make-banana-milkshake-486735">banana milkshake , how to make banana milkshake</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [],
    occasions: [],
    instructions:
      "<p>In a blender, pour in your milk, milo, banana and ice-cream and blend till smooth.Pour into a glass, spray the whipped cream on top and sprinkle the chopped strawberries on top.Serve cool.    For those that asked, here is a link on how to make whipped cream.</p>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "In a blender, pour in your milk, milo, banana and ice-cream and blend till smooth.",
            ingredients: [
              {
                id: 9040,
                name: "banana",
                localizedName: "banana",
                image: "bananas.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
              {
                id: 10014412,
                name: "ice",
                localizedName: "ice",
                image: "ice-cubes.png",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 2,
            step:
              "Pour into a glass, spray the whipped cream on top and sprinkle the chopped strawberries on top.",
            ingredients: [
              {
                id: 1054,
                name: "whipped cream",
                localizedName: "whipped cream",
                image: "whipped-cream.jpg",
              },
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step:
              "Serve cool.    For those that asked, here is a link on how to make whipped cream.",
            ingredients: [
              {
                id: 1054,
                name: "whipped cream",
                localizedName: "whipped cream",
                image: "whipped-cream.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/banana-milo-milkshake-716351",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 3,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 171,
    spoonacularScore: 33.0,
    healthScore: 2.0,
    creditsText: "Afrolems",
    license: "CC BY 4.0",
    sourceName: "Afrolems",
    pricePerServing: 73.98,
    extendedIngredients: [
      {
        id: 2004,
        aisle: "Produce;Spices and Seasonings",
        image: "bay-leaves.jpg",
        consistency: "solid",
        name: "bay leaves",
        nameClean: "bay leaves",
        original: "1 tablespoon of chopped Scent leaves",
        originalString: "1 tablespoon of chopped Scent leaves",
        originalName: "chopped Scent leaves",
        amount: 1.0,
        unit: "tablespoon",
        meta: ["chopped"],
        metaInformation: ["chopped"],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 23572,
        aisle: "Frozen;Meat",
        image: "beef-cubes-raw.png",
        consistency: "solid",
        name: "beef",
        nameClean: "beef",
        original: "8 Pieces of medium Beef (Seasoned and Boiled)",
        originalString: "8 Pieces of medium Beef (Seasoned and Boiled)",
        originalName: "medium Beef (Seasoned and Boiled)",
        amount: 8.0,
        unit: "Pieces",
        meta: ["boiled", "(Seasoned and )"],
        metaInformation: ["boiled", "(Seasoned and )"],
        measures: {
          us: { amount: 8.0, unitShort: "", unitLong: "" },
          metric: { amount: 8.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "solid",
        name: "carrots",
        nameClean: "carrot",
        original: "7 medium pieces of Carrots",
        originalString: "7 medium pieces of Carrots",
        originalName: "Carrots",
        amount: 7.0,
        unit: "medium pieces",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 7.0,
            unitShort: "medium pieces",
            unitLong: "medium pieces",
          },
          metric: {
            amount: 7.0,
            unitShort: "medium pieces",
            unitLong: "medium pieces",
          },
        },
      },
      {
        id: 93605,
        aisle: "Ethnic Foods",
        image: "chili-paste.png",
        consistency: "solid",
        name: "curry paste",
        nameClean: "curry paste",
        original: "1/2 teaspoon of Curry",
        originalString: "1/2 teaspoon of Curry",
        originalName: "Curry",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "1 clove of Garlic",
        originalString: "1 clove of Garlic",
        originalName: "Garlic",
        amount: 1.0,
        unit: "clove",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "clove", unitLong: "clove" },
          metric: {
            amount: 1.0,
            unitShort: "clove",
            unitLong: "clove",
          },
        },
      },
      {
        id: 11216,
        aisle: "Produce;Ethnic Foods;Spices and Seasonings",
        image: "ginger.png",
        consistency: "solid",
        name: "ginger",
        nameClean: "ginger",
        original: "1 teaspoon of grated Ginger",
        originalString: "1 teaspoon of grated Ginger",
        originalName: "grated Ginger",
        amount: 1.0,
        unit: "teaspoon",
        meta: ["grated"],
        metaInformation: ["grated"],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "solid",
        name: "ice cubes",
        nameClean: "ice",
        original: "Seasoning cubes",
        originalString: "Seasoning cubes",
        originalName: "Seasoning",
        amount: 1.0,
        unit: "cubes",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "cubes", unitLong: "cube" },
          metric: {
            amount: 1.0,
            unitShort: "cubes",
            unitLong: "cube",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "solid",
        name: "onion",
        nameClean: "onion",
        original: "1 small bulb of Onion",
        originalString: "1 small bulb of Onion",
        originalName: "bulb of Onion",
        amount: 1.0,
        unit: "small",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "small", unitLong: "small" },
          metric: {
            amount: 1.0,
            unitShort: "small",
            unitLong: "small",
          },
        },
      },
      {
        id: 10011583,
        aisle: "Frozen",
        image: "mixed-vegetables.png",
        consistency: "solid",
        name: "onion and pepper mix",
        nameClean: "pepper and onion mix",
        original:
          "2 cooking spoons of Blended Tatashe-Pepper Mix (Bell peppers and scotch bonnet peppers)",
        originalString:
          "2 cooking spoons of Blended Tatashe-Pepper Mix (Bell peppers and scotch bonnet peppers)",
        originalName:
          "cooking spoons of Blended Tatashe-Pepper Mix (Bell peppers and scotch bonnet peppers)",
        amount: 2.0,
        unit: "",
        meta: ["(Bell peppers and scotch bonnet peppers)"],
        metaInformation: ["(Bell peppers and scotch bonnet peppers)"],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 4513,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "liquid",
        name: "vegetable cooking oil",
        nameClean: "vegetable oil",
        original: "2 Cooking spoons of Vegetable Oil",
        originalString: "2 Cooking spoons of Vegetable Oil",
        originalName: "Cooking spoons of Vegetable Oil",
        amount: 2.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
    ],
    id: 769754,
    title: "Beef Carrot Stew",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.afrolems.com/2016/05/26/beef-carrot-stew/",
    image: "https://spoonacular.com/recipeImages/769754-556x370.jpg",
    imageType: "jpg",
    summary:
      'Beef Carrot Stew might be just the soup you are searching for. For <b>83 cents per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. Watching your figure? This gluten free, dairy free, and whole 30 recipe has <b>101 calories</b>, <b>3g of protein</b>, and <b>4g of fat</b> per serving. If you have seasoning cubes, curry, bulb of onion, and a few other ingredients on hand, you can make it. 171 person were impressed by this recipe. It will be a hit at your <b>Autumn</b> event. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 45%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/oven-braised-beef-stew-with-carrot-parsnip-and-lancinato-kale-43670">Oven-braised Beef Stew With Carrot, Parsnip, And Lancinato Kale</a>, <a href="https://spoonacular.com/recipes/a-winters-walk-beef-and-carrot-stew-with-herb-crusted-dumplings-101808">A Winter\'s Walk Beef and Carrot Stew With Herb Crusted Dumplings</a>, and <a href="https://spoonacular.com/recipes/hearty-beef-stew-a-filling-beef-stew-can-be-made-easily-in-your-crockpot-599542">Hearty Beef Stew – a filling beef stew can be made easily in your crockpot</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: ["gluten free", "dairy free"],
    occasions: ["fall", "winter"],
    instructions:
      "Scrape, wash and boil your carrots till soft.Place in a blender without water and grind till completely shredded.In a pot, heat up your oil and fry your onions, garlic and ginger.Pour in your Tatashe-pepper mix and your beef and allow to simmer on low heat for about 10-15 minutes.Season with curry, seasoning cubes and anything else you may wish to add.Pour in your carrots and stir in and allow to simmer on low heat for another 3-5 minutes.Add your chopped scent leaves and stir in and serve hot with rice, yam, plantain, pasta or any other accompaniment of your choice. ",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Scrape, wash and boil your carrots till soft.",
            ingredients: [
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step:
              "Place in a blender without water and grind till completely shredded.In a pot, heat up your oil and fry your onions, garlic and ginger.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11216,
                name: "ginger",
                localizedName: "ginger",
                image: "ginger.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 3,
            step:
              "Pour in your Tatashe-pepper mix and your beef and allow to simmer on low heat for about 10-15 minutes.Season with curry, seasoning cubes and anything else you may wish to add.",
            ingredients: [
              {
                id: 0,
                name: "seasoning cube",
                localizedName: "seasoning cube",
                image: "stock-cube.jpg",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 2015,
                name: "curry powder",
                localizedName: "curry powder",
                image: "curry-powder.jpg",
              },
              {
                id: 23572,
                name: "beef",
                localizedName: "beef",
                image: "beef-cubes-raw.png",
              },
            ],
            equipment: [],
            length: { number: 15, unit: "minutes" },
          },
          {
            number: 4,
            step:
              "Pour in your carrots and stir in and allow to simmer on low heat for another 3-5 minutes.",
            ingredients: [
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
            ],
            equipment: [],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 5,
            step:
              "Add your chopped scent leaves and stir in and serve hot with rice, yam, plantain, pasta or any other accompaniment of your choice. ",
            ingredients: [
              {
                id: 9277,
                name: "plantain",
                localizedName: "plantain",
                image: "plantains.jpg",
              },
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 11601,
                name: "yam",
                localizedName: "yam",
                image: "sweet-potato.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/beef-carrot-stew-769754",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 8,
    spoonacularScore: 86.0,
    healthScore: 53.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 514.49,
    extendedIngredients: [
      {
        id: 15152,
        aisle: "Seafood",
        image: "shrimp.png",
        consistency: "solid",
        name: "shrimp",
        nameClean: "raw shrimp",
        original: "The Shrimp",
        originalString: "The Shrimp",
        originalName: "The Shrimp",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 15152,
        aisle: "Seafood",
        image: "shrimp.png",
        consistency: "solid",
        name: "shrimp",
        nameClean: "raw shrimp",
        original:
          "About 600gr of large tiger style shrimp (prawns/langoustine) peeled and cleaned",
        originalString:
          "About 600gr of large tiger style shrimp (prawns/langoustine) peeled and cleaned",
        originalName:
          "About of large tiger style shrimp (prawns/langoustine) peeled and cleaned",
        amount: 600.0,
        unit: "gr",
        meta: ["tiger style", "cleaned", "peeled", "(prawns/langoustine)"],
        metaInformation: [
          "tiger style",
          "cleaned",
          "peeled",
          "(prawns/langoustine)",
        ],
        measures: {
          us: { amount: 1.323, unitShort: "lb", unitLong: "pounds" },
          metric: { amount: 600.0, unitShort: "gr", unitLong: "grs" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic cloves",
        nameClean: "garlic",
        original: "2 x garlic cloves, crushed",
        originalString: "2 x garlic cloves, crushed",
        originalName: "x garlic cloves, crushed",
        amount: 2.0,
        unit: "",
        meta: ["crushed"],
        metaInformation: ["crushed"],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 x tbsp olive oil",
        originalString: "1 x tbsp olive oil",
        originalName: "x tbsp olive oil",
        amount: 1.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9160,
        aisle: "Produce",
        image: "lime-juice.png",
        consistency: "liquid",
        name: "juice of lime",
        nameClean: "lime juice",
        original: "Juice of 1 lime",
        originalString: "Juice of 1 lime",
        originalName: "Juice of lime",
        amount: 1.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and Pepper",
        originalString: "Salt and Pepper",
        originalName: "Salt and Pepper",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 21052,
        aisle: "Produce",
        image: "mixed-greens-or-mesclun.jpg",
        consistency: "solid",
        name: "salad mix",
        nameClean: "greens",
        original: "The Salad",
        originalString: "The Salad",
        originalName: "The Salad",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 10111251,
        aisle: "Produce",
        image: "romaine.jpg",
        consistency: "solid",
        name: "Cos lettuce",
        nameClean: "romaine",
        original: "The leaves of 1 medium Cos lettuce finely shredded",
        originalString: "The leaves of 1 medium Cos lettuce finely shredded",
        originalName: "The leaves of Cos lettuce finely shredded",
        amount: 1.0,
        unit: "medium",
        meta: ["shredded", "finely"],
        metaInformation: ["shredded", "finely"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "medium",
            unitLong: "medium",
          },
          metric: {
            amount: 1.0,
            unitShort: "medium",
            unitLong: "medium",
          },
        },
      },
      {
        id: 2044,
        aisle: "Produce;Spices and Seasonings",
        image: "basil.jpg",
        consistency: "solid",
        name: "basil leaves",
        nameClean: "basil",
        original: "6/8 basil leaves chopped",
        originalString: "6/8 basil leaves chopped",
        originalName: "basil leaves chopped",
        amount: 0.75,
        unit: "",
        meta: ["chopped"],
        metaInformation: ["chopped"],
        measures: {
          us: { amount: 0.75, unitShort: "", unitLong: "" },
          metric: { amount: 0.75, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11168,
        aisle: "Produce",
        image: "corn.png",
        consistency: "solid",
        name: "sweet corn",
        nameClean: "corn",
        original: "200gr sweet corn",
        originalString: "200gr sweet corn",
        originalName: "sweet corn",
        amount: 200.0,
        unit: "gr",
        meta: ["sweet"],
        metaInformation: ["sweet"],
        measures: {
          us: { amount: 7.055, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 200.0, unitShort: "gr", unitLong: "grs" },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "solid",
        name: "spring onions",
        nameClean: "spring onions",
        original: "3 x spring onions (scallions) chopped finely",
        originalString: "3 x spring onions (scallions) chopped finely",
        originalName: "x spring onions (scallions) chopped finely",
        amount: 3.0,
        unit: "",
        meta: ["chopped", "finely", "(scallions)"],
        metaInformation: ["chopped", "finely", "(scallions)"],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9266,
        aisle: "Produce",
        image: "pineapple.jpg",
        consistency: "solid",
        name: "pineapple",
        nameClean: "pineapple",
        original: "600gr fresh pineapple cut into small cubes",
        originalString: "600gr fresh pineapple cut into small cubes",
        originalName: "fresh pineapple cut into small cubes",
        amount: 600.0,
        unit: "gr",
        meta: ["fresh", "cut into small cubes"],
        metaInformation: ["fresh", "cut into small cubes"],
        measures: {
          us: { amount: 1.323, unitShort: "lb", unitLong: "pounds" },
          metric: { amount: 600.0, unitShort: "gr", unitLong: "grs" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocados",
        nameClean: "hass avocado",
        original: "2 x avocados chopped into cubes",
        originalString: "2 x avocados chopped into cubes",
        originalName: "x avocados chopped into cubes",
        amount: 2.0,
        unit: "",
        meta: ["chopped"],
        metaInformation: ["chopped"],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "hass avocado",
        original: "Avocado",
        originalString: "Avocado",
        originalName: "Avocado",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 43016,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "coleslaw-or-caesar-dressing.jpg",
        consistency: "solid",
        name: "slaw dressing",
        nameClean: "coleslaw dressing",
        original: "The Dressing",
        originalString: "The Dressing",
        originalName: "The Dressing",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "3 x tbsp olive oil",
        originalString: "3 x tbsp olive oil",
        originalName: "x tbsp olive oil",
        amount: 3.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 19296,
        aisle: "Nut butters, Jams, and Honey",
        image: "honey.png",
        consistency: "liquid",
        name: "honey",
        nameClean: "honey",
        original: "3 x tbsp honey",
        originalString: "3 x tbsp honey",
        originalName: "x tbsp honey",
        amount: 3.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9160,
        aisle: "Produce",
        image: "lime-juice.png",
        consistency: "liquid",
        name: "juice of lime",
        nameClean: "lime juice",
        original: "Juice and zest of 3 limes",
        originalString: "Juice and zest of 3 limes",
        originalName: "Juice and zest of limes",
        amount: 3.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
    ],
    id: 659927,
    title: "Shrimp and Avocado Salad",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/ZTNWCWQP/shrimp-and-avocado-salad",
    image: "https://spoonacular.com/recipeImages/659927-556x370.jpg",
    imageType: "jpg",
    summary:
      'Shrimp and Avocado Salad might be a good recipe to expand your main course collection. One serving contains <b>502 calories</b>, <b>36g of protein</b>, and <b>23g of fat</b>. This recipe serves 4. For <b>$5.14 per serving</b>, this recipe <b>covers 38%</b> of your daily requirements of vitamins and minerals. A mixture of basil leaves, avocados into cubes, the salad, and a handful of other ingredients are all it takes to make this recipe so tasty. 7 people have tried and liked this recipe. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. It is brought to you by Foodista. It is a good option if you\'re following a <b>gluten free, dairy free, and pescatarian</b> diet. With a spoonacular <b>score of 86%</b>, this dish is amazing. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/shrimp-corn-california-avocado-pasta-salad-a-ca-avocado-trip-584558">Shrimp, Corn & Californian Avocado Pasta Salad & a CAn Avocado Trip</a>, <a href="https://spoonacular.com/recipes/shrimp-and-avocado-salad-770494">Shrimp and Avocado Salad</a>, and <a href="https://spoonacular.com/recipes/shrimp-and-avocado-salad-245506">Shrimp and Avocado Salad</a>.',
    cuisines: [],
    dishTypes: [
      "side dish",
      "lunch",
      "main course",
      "salad",
      "main dish",
      "dinner",
    ],
    diets: ["gluten free", "dairy free", "pescatarian"],
    occasions: [],
    instructions:
      "1.Firstly, to cook the shrimp, heat the olive oil in a pan and once hot add the shrimp crushed garlic and chili flakes. It is important to get the oil nice and hot (not smoking, just before that point) your shrimp should sizzle when added to the pan. Check the back of the shrimp and when you see the colour change about half way up, turn them over. Do the same on the other side. This should only take a minute to two minutes maximum on both sides  otherwise you will get a rubbery result if you leave it too long. Squeeze over the lime juice  this too should bubble and reduce. Add a little salt and pepper, stir through, remove from the heat and set aside.\n2.Mix the dressing ingredients together, check for flavour, adjust if need be and set aside.\n3.Place all the salad ingredients in a bowl except the avocado and the salt and pepper. Prepare the avocado as you are about to serve otherwise it will turn brown. Once it is covered in the lime dressing, this will slow down the oxidization process and it wont go brown so easily.\n4.When you are ready to serve mix  of the avocado through the salad and add the dressing. Toss everything together. Taste to see if you need any salt and pepper. Place your shrimp on top of the salad with the rest of the avocado and sprinkle/pour any residue from the pan over your salad in which you cooked the shrimp. This is great flavour, so you dont want to lose it.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Firstly, to cook the shrimp, heat the olive oil in a pan and once hot add the shrimp crushed garlic and chili flakes. It is important to get the oil nice and hot (not smoking, just before that point) your shrimp should sizzle when added to the pan. Check the back of the shrimp and when you see the colour change about half way up, turn them over. Do the same on the other side. This should only take a minute to two minutes maximum on both sides  otherwise you will get a rubbery result if you leave it too long. Squeeze over the lime juice  this too should bubble and reduce.",
            ingredients: [
              {
                id: 1032009,
                name: "red pepper flakes",
                localizedName: "red pepper flakes",
                image: "red-pepper-flakes.jpg",
              },
              {
                id: 9160,
                name: "lime juice",
                localizedName: "lime juice",
                image: "lime-juice.png",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 15152,
                name: "shrimp",
                localizedName: "shrimp",
                image: "shrimp.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: { number: 2, unit: "minutes" },
          },
          {
            number: 2,
            step:
              "Add a little salt and pepper, stir through, remove from the heat and set aside.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step:
              "Mix the dressing ingredients together, check for flavour, adjust if need be and set aside.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 4,
            step:
              "Place all the salad ingredients in a bowl except the avocado and the salt and pepper. Prepare the avocado as you are about to serve otherwise it will turn brown. Once it is covered in the lime dressing, this will slow down the oxidization process and it wont go brown so easily.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 9159,
                name: "lime",
                localizedName: "lime",
                image: "lime.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 5,
            step:
              "When you are ready to serve mix  of the avocado through the salad and add the dressing. Toss everything together. Taste to see if you need any salt and pepper.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step:
              "Place your shrimp on top of the salad with the rest of the avocado and sprinkle/pour any residue from the pan over your salad in which you cooked the shrimp. This is great flavour, so you dont want to lose it.",
            ingredients: [
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 15152,
                name: "shrimp",
                localizedName: "shrimp",
                image: "shrimp.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/shrimp-and-avocado-salad-659927",
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    weightWatcherSmartPoints: 17,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1072,
    spoonacularScore: 48.0,
    healthScore: 4.0,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 128.22,
    extendedIngredients: [
      {
        id: 1017,
        aisle: "Cheese",
        image: "cream-cheese.jpg",
        consistency: "solid",
        name: "cream cheese",
        nameClean: "cream cheese",
        original: "2 ounces cream cheese",
        originalString: "2 ounces cream cheese",
        originalName: "cream cheese",
        amount: 2.0,
        unit: "ounces",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 2.0, unitShort: "oz", unitLong: "ounces" },
          metric: {
            amount: 56.699,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 98897,
        aisle: "Dried Fruits;Produce",
        image: "freeze-dried-strawberries.jpg",
        consistency: "solid",
        name: "dried strawberries",
        nameClean: "dried strawberries",
        original: "24 strawberries, cleaned and dried",
        originalString: "24 strawberries, cleaned and dried",
        originalName: "strawberries, cleaned and dried",
        amount: 24.0,
        unit: "",
        meta: ["dried", "cleaned"],
        metaInformation: ["dried", "cleaned"],
        measures: {
          us: { amount: 24.0, unitShort: "", unitLong: "" },
          metric: { amount: 24.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 19296,
        aisle: "Nut butters, Jams, and Honey",
        image: "honey.png",
        consistency: "liquid",
        name: "honey",
        nameClean: "honey",
        original: "1-2 tsp honey",
        originalString: "1-2 tsp honey",
        originalName: "honey",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 9156,
        aisle: "Produce",
        image: "zest-lemon.jpg",
        consistency: "solid",
        name: "lemon zest",
        nameClean: "lemon peel",
        original: "1/4 tsp lemon zest",
        originalString: "1/4 tsp lemon zest",
        originalName: "lemon zest",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 19336,
        aisle: "Baking",
        image: "powdered-sugar.jpg",
        consistency: "solid",
        name: "powdered sugar",
        nameClean: "powdered sugar",
        original: "2 T powdered sugar",
        originalString: "2 T powdered sugar",
        originalName: "powdered sugar",
        amount: 2.0,
        unit: "T",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 1036,
        aisle: "Cheese",
        image: "ricotta.png",
        consistency: "solid",
        name: "ricotta",
        nameClean: "ricotta cheese",
        original: "1 1/4 cup good quality ricotta",
        originalString: "1 1/4 cup good quality ricotta",
        originalName: "good quality ricotta",
        amount: 1.25,
        unit: "cup",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.25, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 295.735,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2050,
        aisle: "Baking",
        image: "vanilla-extract.jpg",
        consistency: "liquid",
        name: "vanilla",
        nameClean: "vanilla extract",
        original: "1/2 tsp vanilla",
        originalString: "1/2 tsp vanilla",
        originalName: "vanilla",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 716409,
    title: "Cannoli Cream-Filled Strawberries",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2013/02/cannoli-cream-filled-strawberries.html",
    image: "https://spoonacular.com/recipeImages/716409-556x370.jpg",
    imageType: "jpg",
    summary:
      'This recipe makes 2 servings with <b>454 calories</b>, <b>19g of protein</b>, and <b>30g of fat</b> each. For <b>$1.36 per serving</b>, this recipe <b>covers 10%</b> of your daily requirements of vitamins and minerals. Plenty of people made this recipe, and 1072 would say it hit the spot. Head to the store and pick up cream cheese, strawberries, ricotta, and a few other things to make it today. It is a good option if you\'re following a <b>gluten free and vegetarian</b> diet. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 51%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/cannoli-cream-filled-strawberries-552981">Cannoli Cream-Filled Strawberries</a>, <a href="https://spoonacular.com/recipes/strawberries-with-cannoli-cream-dip-57842">Strawberries With Cannoli Cream Dip</a>, and <a href="https://spoonacular.com/recipes/cream-filled-cannoli-cupcakes-176206">Cream-Filled Cannoli Cupcakes</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    instructions: "",
    analyzedInstructions: [],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/cannoli-cream-filled-strawberries-716409",
  },
];
